# Generated by Django 2.1.5 on 2020-05-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderslist',
            name='extras',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
